import{v4 as uuid} from "https://jspm.dev/uuid";
export const products=[{
    id:uuid(),
    name:"tshirt",
    img:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/p/h/h/s-ts29-vebnor-original-imah3dvquaq8hhar.jpeg?q=70",
    alt:"mens shirt",
    brand:"allen solly",
    newprice:1230,
    oldprice:2500,
    discount:67,
    size:"L",
    idealfor:"M",
    rating:4.1,

},
{
    id:uuid(),
    name:"shoes",
    img:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/p/h/h/s-ts29-vebnor-original-imah3dvquaq8hhar.jpeg?q=70",
    alt:"mens shirt",
    brand:"allen solly",
    newprice:1230,
    oldprice:2500,
    discount:67,
    size:"L",
    idealfor:"M",
    rating:4.1,
},
{
    id:uuid(),
    name:"tshirt",
    img:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/p/h/h/s-ts29-vebnor-original-imah3dvquaq8hhar.jpeg?q=70",
    alt:"mens shirt",
    brand:"allen solly",
    newprice:1230,
    oldprice:2500,
    discount:67,
    size:"L",
    idealfor:"M",
    rating:4.1,
},
{
    id:uuid(),
    name:"tshirt",
    img:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/p/h/h/s-ts29-vebnor-original-imah3dvquaq8hhar.jpeg?q=70",
    alt:"mens shirt",
    brand:"allen solly",
    newprice:1230,
    oldprice:2500,
    discount:67,
    size:"L",
    idealfor:"M",
    rating:4.1,
}
]